const Lsi = {
  menu: {
    about: {
      en: "About",
      uk: "Про застосунок",
    },
    home: {
      en: "Home",
      uk: "Домашня",
    },
    admin: {
      en: "Admin",
      uk: "Адмінка",
    },
  },
  about: {
    header: {
      en: "uuPlaces",
    },
    creatorsHeader: {
      en: "Application creators",
      uk: "Творці застосунку",
    },
  },
  user: { en: "User", uk: "Користувач" },
  parkingPlace: { en: "Parking Place", uk: "Місце парковки" },
  reservationDates: { en: "Reservation Dates", uk: "Дати резерву" },
  reservationDuration: { en: "Reservation Duration", uk: "Тривалість резерву" },
  confirmDelete: {
    en: "Your reservation will be deleted.",
    uk: "Ваш резерв буде видалено.",
  },
  areYouSure: {
    en: "Are you sure?",
    uk: "Ви впевнені?",
  },
  days: {
    en: "${days} days",
    uk: "${days} днів",
  },

  create: { en: "Create", uk: "Створити" },
  update: { en: "Update", uk: "Оновити" },
  delete: { en: "Delete", uk: "Видалити" },
  cancel: { en: "Cancel", uk: "Відмінити" },
  createReservation: { en: "Create reservation", uk: "Створити резерв" },
  reservationUpdate: { en: "Reservation update", uk: "Оновити резерв" },
  reservationDelete: { en: "Reservation delete", uk: "Видалити резерв" },
  reservationDeleteConfirmation: {
    en: "Are you sure you want to delete this reservation?",
    uk: "Ви впевнені що хочете видалити цей резерв?",
  },
  successMessageCreated: {
    en: "Reservation successfully created",
    uk: "Резерв успішно створено",
  },
  successMessageUpdated: {
    en: "Reservation successfully updated",
    uk: "Резерв успішно оновлено",
  },
  successMessageDeleted: {
    en: "Reservation successfully deleted",
    uk: "Резерв успішно видалено",
  },
  reservations: { en: "Reservations", uk: "Резерви" },
  weeklyOverview: { en: "Weekly Overview", uk: "Тижневий огляд" },
  yourParkingPlace: { en: "Your parking place: ${number}", uk: "Ваше паркувальне місце: ${number}" },
  noReservation: { en: "Today you don't have reservations.", uk: "Сьогодні у вас немає резервів" },
  notOpened: { en: "Reservation will be opened on", uk: "Резервація буде відкрита" },
  sendNotification: { en: "Send notification", uk: "Відправити повідомлення про звільнене місце" },
  reservedBy: { en: "Reserved by: ", uk: "Зарезервовано: " },
  emptyPlace: { en: "Empty place", uk: "Вільне місце" },
  dayFrom: { en: "Day from", uk: "Початкова дата" },
  dayTo: { en: "Day to", uk: "Кінцева дата" },
  undergroundParkingLots: {
    en: "Underground parking lots",
    uk: "Підземні місця",
  },
  surfaceParkingLots: {
    en: "Surface parking lots",
    uk: "Надземні місця",
  },
  usersList: { en: "Users List", uk: "Список користувачів" },
  parkingPlaces: { en: "Parking Lots", uk: "Паркувальні місця" },
  settings: { en: "Settings", uk: "Налаштування" },
  userSuccessfullyCreated: {
    en: "User successfully created",
    uk: "Користувач успішно створений",
  },
  userSuccessfullyUpdated: {
    en: "User successfully updated",
    uk: "Користувача успішно оновлено",
  },
  transport: { en: "Transport", uk: "Транспортний засіб" },
  transportNumber: { en: "Transport number", uk: "Номерний знак" },
  transportType: { en: "Transport type", uk: "Тип транспорту" },
  createUser: { en: "Create new user", uk: "Створити нового користувача" },
  userUpdate: { en: "Update user", uk: "Оновити користувача" },
  userInfo: { en: "User info", uk: "Інформація про користувача" },
  transportInfo: { en: "Transport info", uk: "Інформація про транспортний засіб" },
  uuIdentity: { en: "uuIdentity" },
  type: { en: "Type", uk: "Тип" },
  status: { en: "Status", uk: "Статус" },
  blocked: { en: "Blocked", uk: "Заблоковано" },
  block: { en: "Block", uk: "Заблокувати" },
  unBlock: { en: "Unblock", uk: "Розблокувати" },
  free: { en: "Free", uk: "Вільне" },
  successfullyUnblocked: { en: "Parking lot successfully unblocked", uk: "Парковочне місце успішно розблоковано" },
  successfullyBlocked: { en: "Parking lot successfully blocked", uk: "Парковочне місце успішно заблоковано" },
  model: { en: "Model", uk: "Модель" },
  brand: { en: "Brand", uk: "Бренд" },
  number: { en: "Number", uk: "Номер" },
  userCreatePlaceHolders: {
    uuIdentity: { en: "8517-626-1" },
    model: { en: "i3" },
    brand: { en: "BMW" },
    number: { en: "AA1111OO" },
  },
  underground: { en: "Underground", uk: "Підземне" },
  surface: { en: "Surface", uk: "Надземне" },
  createParkingPlace: { en: "Create Parking Place", uk: "Створити парко місце" },
  parkingPlaceUpdate: { en: "Parking Place Update", uk: "Оновити парко місце" },
  parkingPlaceSuccessfullyCreated: {
    en: "Parking place successfully created",
    uk: "Парко місцеуспішно створено",
  },
  parkingPlaceSuccessfullyUpdated: {
    en: "Parking place successfully updated",
    uk: "Парко місце успішно оновлено",
  },
  dayOfStartReservations: { en: "Day of reservation start", uk: "Дата старту можливості резервації" },
  hourOfStartReservations: { en: "Hour of reservation start", uk: "Годиина старту можливості резервації" },
  message: { en: "Message", uk: "Повідомлення" },
  formHeader: { en: "Reservations configuration", uk: "Налаштування резервування" },
  sendMessageFormHeader: { en: "Send message to telegram", uk: "Відправити повідомлення в телеграм" },
  successAppUpdate: { en: "Application has been successfully updated", uk: "Застосунок успішно оновлено" },
  successMessageSend: { en: "Message has been successfully sent", uk: "Повідомлення успішно відправлено" },
  userDelete: { en: "Delete user", uk: "Видалити користувача" },
  successMessageUserDeleted: {
    en: "User successfully deleted",
    uk: "Користувач успішно видалено",
  },
};

export default Lsi;
